"use server";

import { syllabusGenerator, type SyllabusOutput } from "@/ai/flows/syllabus-generator";
import { unstable_cache } from "next/cache";
import { getFallbackSyllabus } from "@/lib/syllabus-fallback";

/**
 * Server Action to fetch or generate a syllabus for a given query.
 * Implements a robust caching layer and graceful fallback to static data.
 */

interface SyllabusResponse {
    data: SyllabusOutput;
    source: 'ai' | 'fallback';
}

const getCachedSyllabus = unstable_cache(
    async (query: string): Promise<SyllabusResponse> => {
        console.log(`[SyllabusAction] Fetching syllabus for: "${query}"`);
        try {
            const result = await syllabusGenerator({ query });

            if (!result || !result.structure) {
                throw new Error("Empty or invalid syllabus structure generated by AI");
            }

            return {
                data: result,
                source: 'ai'
            };
        } catch (error) {
            console.error('[SYLLABUS_ERROR] AI Generation failed, invoking fallback.', {
                message: error instanceof Error ? error.message : 'Unknown error',
                query,
            });

            return {
                data: getFallbackSyllabus(query),
                source: 'fallback'
            };
        }
    },
    ['syllabus-generator-v2'], // Versioned cache key
    {
        revalidate: 86400, // 24 hours
        tags: ['syllabus']
    }
);

export async function getSyllabus(query: string): Promise<SyllabusResponse | null> {
    try {
        return await getCachedSyllabus(query);
    } catch (error) {
        console.error("[SYLLABUS_CRITICAL_ERROR] Cache retrieval failed:", error);
        // Absolute last resort fallback
        return {
            data: getFallbackSyllabus(query),
            source: 'fallback'
        };
    }
}
