"use server";

import { syllabusGenerator } from "@/ai/flows/syllabus-generator";
import { unstable_cache } from "next/cache";
import { getFallbackSyllabus } from "@/lib/syllabus-fallback";

// Cache the syllabus generator result for improved performance
// Cache key depends on the query argument automatically
const getCachedSyllabus = unstable_cache(
    async (query: string) => {
        try {
            const result = await syllabusGenerator({ query });
            if (!result || !result.structure) {
                throw new Error("Empty syllabus generated by AI");
            }
            return result;
        } catch (error) {
            console.error('SYLLABUS_FLOW_FAILED', {
                message: error instanceof Error ? error.message : 'Unknown error',
                stack: error instanceof Error ? error.stack : undefined,
                query,
            });
            // Return high-quality fallback syllabus
            return getFallbackSyllabus(query);
        }
    },
    ['syllabus-generator'],
    {
        revalidate: 86400, // 24 hours
        tags: ['syllabus']
    }
);

export async function getSyllabus(query: string) {
    try {
        return await getCachedSyllabus(query);
    } catch (error) {
        console.error("Error fetching syllabus:", error);
        return null;
    }
}
