"use server";

export const runtime = 'nodejs';

import { generateQuiz, type AdaptiveQuizInput } from "@/ai/flows/adaptive-quiz-engine";
import { unstable_cache } from "next/cache";
import { getFallbackQuiz } from "@/lib/quiz-fallback";

// Cache generated quizzes to reduce AI costs and latency
// Input arguments (topic, difficulty, etc.) are automatically part of the cache key
const getCachedQuiz = unstable_cache(
  async (values: AdaptiveQuizInput) => {
    try {
      const result = await generateQuiz(values);
      if (!result || !result.quiz || result.quiz.length === 0) {
        throw new Error("Empty quiz generated by AI");
      }
      return result;
    } catch (error) {
      console.error("[QUIZ_ERROR] AI Generation failed:", {
        error: error instanceof Error ? error.message : 'Unknown error',
        stack: error instanceof Error ? error.stack : undefined,
        topic: values.topic
      });
      // Return fallback quiz but don't throw, so the user still gets a quiz
      return getFallbackQuiz(values.topic, values.numQuestions);
    }
  },
  ['adaptive-quiz-generator'],
  {
    revalidate: 3600, // 1 hour
    tags: ['quiz']
  }
);

export async function createQuiz(values: AdaptiveQuizInput) {
  return await getCachedQuiz(values);
}
