/**
 * SANKALP-AEI Agent System — Orchestrator
 * The master brain that coordinates: Plan → Execute → Review → Debug → Improve → Commit
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import { PoolManager } from '../llm/pool-manager.js';
import { PromptBuilder } from '../llm/prompt-builder.js';
import { type AgentConfig, type FileChange } from '../llm/models.js';
import { Planner } from './planner.js';
import { Dispatcher } from './dispatcher.js';
import { ReviewPipeline } from './reviewer.js';
import { FsTools } from '../utils/fs-tools.js';
import { GitTools } from '../utils/git-tools.js';
import { logger } from '../utils/logger.js';

export interface OrchestratorResult {
  success: boolean;
  branch?: string;
  commitSha?: string;
  totalTokens: number;
  filesChanged: string[];
  report: string;
  durationMs: number;
}

export class Orchestrator {
  private config: AgentConfig;
  private pool: PoolManager;
  private promptBuilder: PromptBuilder;
  private planner: Planner;
  private dispatcher: Dispatcher;
  private reviewer: ReviewPipeline;
  private fs: FsTools;
  private git: GitTools;

  constructor(config: AgentConfig) {
    this.config = config;

    // Load env vars from .env.agents
    this.loadEnv();

    // Initialize components
    this.pool = new PoolManager();
    this.promptBuilder = new PromptBuilder(config.projectRoot);
    this.fs = new FsTools(config.projectRoot);
    this.fs.ensureOutputDirs();
    this.git = new GitTools(config.projectRoot, config.branchPrefix);

    this.planner = new Planner(this.pool, this.promptBuilder, config.projectRoot);
    this.dispatcher = new Dispatcher(this.pool, this.promptBuilder, this.fs, config.projectRoot);
    this.reviewer = new ReviewPipeline(this.pool, this.fs, config.projectRoot);
  }

  /**
   * Execute a complete task from natural language description.
   * Pipeline: Plan → Execute → Review → Debug → Validate → Improve → Commit
   */
  async run(taskDescription: string, options?: { dryRun?: boolean }): Promise<OrchestratorResult> {
    const startTime = Date.now();
    let totalTokens = 0;

    logger.header('SANKALP-AEI Agent Orchestrator');
    logger.info(`Task: "${taskDescription}"`, 'orchestrator');
    logger.info(`Keys loaded: ${this.pool.totalKeys}/30`, 'orchestrator');
    logger.info(`Mode: ${options?.dryRun ? 'DRY RUN' : 'LIVE'}`, 'orchestrator');
    logger.separator();

    try {
      // ═══════════════════════════════════════════════════
      // PHASE 1: PLANNING
      // ═══════════════════════════════════════════════════
      const graph = await this.planner.plan(taskDescription);
      const planStats = graph.getStats();
      logger.info(`Plan: ${planStats.total} subtasks created`, 'orchestrator');

      if (options?.dryRun) {
        const report = graph.generateReport();
        this.saveReport('dry-run', report);
        return {
          success: true,
          totalTokens: 0,
          filesChanged: [],
          report,
          durationMs: Date.now() - startTime,
        };
      }

      // ═══════════════════════════════════════════════════
      // PHASE 2: EXECUTION
      // ═══════════════════════════════════════════════════
      const { results, totalTokens: execTokens } = await this.dispatcher.executeGraph(graph);
      totalTokens += execTokens;

      // Collect all file changes
      const allFiles: FileChange[] = [];
      for (const result of results) {
        allFiles.push(...result.files);
      }

      if (allFiles.length === 0) {
        logger.warn('No files were generated by any agent', 'orchestrator');
        return {
          success: false,
          totalTokens,
          filesChanged: [],
          report: 'No files generated',
          durationMs: Date.now() - startTime,
        };
      }

      logger.info(`Execution complete: ${allFiles.length} files generated`, 'orchestrator');

      // ═══════════════════════════════════════════════════
      // PHASE 3: REVIEW + DEBUG + VALIDATE + IMPROVE
      // ═══════════════════════════════════════════════════
      logger.header('Quality Assurance Pipeline');
      const qa = await this.reviewer.runPipeline(allFiles, taskDescription);
      totalTokens += qa.totalTokens;

      // Merge improved files into allFiles
      if (qa.improvedFiles.length > 0) {
        logger.info(`Applied ${qa.improvedFiles.length} improvements`, 'orchestrator');
        allFiles.push(...qa.improvedFiles);
      }

      logger.info(
        `QA Result: ${qa.approved ? '✅ APPROVED' : '⚠️ CONDITIONALLY APPROVED'} (score: ${qa.review.score}/100)`,
        'orchestrator'
      );

      // ═══════════════════════════════════════════════════
      // PHASE 4: COMMIT
      // ═══════════════════════════════════════════════════
      if (this.config.autoCommit) {
        logger.header('Commit Phase');

        // Create feature branch
        const branchName = await this.git.createBranch(this.sanitizeBranchName(taskDescription));

        // Stage all modified files
        const filePaths = [...new Set(allFiles.map(f => f.path))];
        await this.git.stageFiles(filePaths);

        // Build commit message
        const commitMessage = this.buildCommitMessage(taskDescription, graph.getStats(), qa.review.score);
        const sha = await this.git.commit(commitMessage);

        logger.info(`Committed to ${branchName}: ${sha.slice(0, 8)}`, 'orchestrator');

        // Generate and save report
        const report = this.buildFinalReport(graph, results, qa, branchName, sha, totalTokens, Date.now() - startTime);
        this.saveReport(branchName, report);

        // Print summary
        this.printFinalSummary(graph.getStats(), totalTokens, allFiles.length, branchName, qa.review.score, Date.now() - startTime);

        return {
          success: true,
          branch: branchName,
          commitSha: sha,
          totalTokens,
          filesChanged: filePaths,
          report,
          durationMs: Date.now() - startTime,
        };
      }

      // No auto-commit: just report
      const report = graph.generateReport();
      this.saveReport('no-commit', report);

      return {
        success: true,
        totalTokens,
        filesChanged: allFiles.map(f => f.path),
        report,
        durationMs: Date.now() - startTime,
      };
    } catch (error) {
      const msg = (error as Error).message;
      logger.error(`Orchestrator failed: ${msg}`, 'orchestrator');
      return {
        success: false,
        totalTokens,
        filesChanged: [],
        report: `ERROR: ${msg}`,
        durationMs: Date.now() - startTime,
      };
    }
  }

  /** Show pool statistics */
  showStats(): void {
    const stats = this.dispatcher.getPoolStats();
    logger.header('API Key Pool Statistics');
    for (const [tier, data] of Object.entries(stats)) {
      logger.info(
        `${tier}: ${data.available}/${data.loaded} available | ${data.totalCalls} calls | ${data.totalTokens.toLocaleString()} tokens`,
        'system'
      );
    }
  }

  // ─── Private helpers ──────────────────────────────────

  private loadEnv(): void {
    const envPath = join(this.config.projectRoot, 'agents', '.env.agents');
    try {
      const content = readFileSync(envPath, 'utf-8');
      for (const line of content.split('\n')) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#')) continue;
        const eqIndex = trimmed.indexOf('=');
        if (eqIndex > 0) {
          const key = trimmed.slice(0, eqIndex).trim();
          const value = trimmed.slice(eqIndex + 1).trim();
          if (value) process.env[key] = value;
        }
      }
      logger.debug('Loaded .env.agents', 'system');
    } catch {
      logger.warn('No .env.agents found — using existing environment variables', 'system');
    }
  }

  private sanitizeBranchName(task: string): string {
    return task
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, '')
      .replace(/\s+/g, '-')
      .slice(0, 40);
  }

  private buildCommitMessage(
    task: string,
    stats: { total: number; completed: number; failed: number },
    reviewScore: number
  ): string {
    const lines = [
      `feat(agents): ${task.slice(0, 72)}`,
      '',
      `Auto-generated by SANKALP-AEI Agent Orchestrator`,
      `Tasks: ${stats.completed}/${stats.total} completed (${stats.failed} failed)`,
      `Review Score: ${reviewScore}/100`,
      '',
      `Model Pool: 30 Gemini keys (20 Pro + 5 NanoPro + 5 Flash)`,
    ];
    return lines.join('\n');
  }

  private buildFinalReport(
    graph: import('../tasks/task-graph.js').TaskGraphManager,
    results: import('../agents/base-agent.js').AgentExecutionResult[],
    qa: { review: { score: number; issues: string[] }; validation: import('../llm/models.js').ValidationResult },
    branch: string,
    sha: string,
    totalTokens: number,
    durationMs: number
  ): string {
    const taskReport = graph.generateReport();

    // Collect skills loaded across all agent executions
    const skillsSummary: string[] = [];
    for (const r of results) {
      if (r.skillsLoaded && r.skillsLoaded.length > 0) {
        skillsSummary.push(`- **${r.agentRole}**: ${r.skillsLoaded.join(', ')}`);
      }
    }

    const lines = [
      `# Agent Orchestration Report`,
      ``,
      `**Branch:** ${branch}`,
      `**Commit:** ${sha.slice(0, 8)}`,
      `**Duration:** ${(durationMs / 1000).toFixed(1)}s`,
      `**Total Tokens:** ${totalTokens.toLocaleString()}`,
      `**Review Score:** ${qa.review.score}/100`,
      ``,
      `## Skills Injected`,
      ...(skillsSummary.length > 0 ? skillsSummary : ['- No dynamic skills loaded']),
      ``,
      `## QA Results`,
      `- Typecheck: ${qa.validation.typecheckPassed ? '✅' : '❌'}`,
      `- Tests: ${qa.validation.testsPassed ? '✅' : '❌'}`,
      `- Lint: ${qa.validation.lintPassed ? '✅' : '❌'}`,
      ``,
      `### Issues`,
      ...qa.review.issues.map(i => `- ${i}`),
      ``,
      `---`,
      ``,
      taskReport,
    ];
    return lines.join('\n');
  }

  private saveReport(name: string, content: string): void {
    const reportsDir = join(this.config.projectRoot, 'agents', 'output', 'reports');
    mkdirSync(reportsDir, { recursive: true });
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const filename = `${timestamp}__${name.replace(/[^a-z0-9-]/gi, '_')}.md`;
    writeFileSync(join(reportsDir, filename), content, 'utf-8');
    logger.info(`Report saved: output/reports/${filename}`, 'system');
  }

  private printFinalSummary(
    stats: { total: number; completed: number; failed: number },
    totalTokens: number,
    filesChanged: number,
    branch: string,
    reviewScore: number,
    durationMs: number
  ): void {
    logger.separator('═');
    logger.info('', 'orchestrator');
    logger.info(`  ✅ ORCHESTRATION COMPLETE`, 'orchestrator');
    logger.info(`  ─────────────────────────`, 'orchestrator');
    logger.info(`  Branch:       ${branch}`, 'orchestrator');
    logger.info(`  Tasks:        ${stats.completed}/${stats.total} completed`, 'orchestrator');
    logger.info(`  Files:        ${filesChanged} changed`, 'orchestrator');
    logger.info(`  Tokens:       ${totalTokens.toLocaleString()}`, 'orchestrator');
    logger.info(`  Review Score: ${reviewScore}/100`, 'orchestrator');
    logger.info(`  Duration:     ${(durationMs / 1000).toFixed(1)}s`, 'orchestrator');
    logger.info('', 'orchestrator');
    logger.separator('═');
  }
}
