/**
 * SANKALP-AEI Agent System — Backend Agent
 * Specializes in Express routes, Firestore, services, and core engine.
 * Enhanced with dynamic skill injection for TypeScript, Zod, Firebase, etc.
 */

import { BaseAgent, type AgentExecutionResult } from './base-agent.js';
import { AgentRole, type TaskNode } from '../llm/models.js';
import { logger } from '../utils/logger.js';

export class BackendAgent extends BaseAgent {
  async execute(task: TaskNode): Promise<AgentExecutionResult> {
    logger.info(`⚙️ Starting: ${task.name}`, this.role);
    let totalTokens = 0;

    const { systemPrompt, userPrompt, skillsLoaded } = this.buildPrompt(
      `You are building the backend for SANKALP-AEI, an adaptive educational intelligence system.

## Task
${task.description}

## Requirements
1. TypeScript strict mode, NO \`any\` types
2. Use Zod for all runtime data validation at API boundaries
3. Apply RBAC middleware (\`requireRole\`) on every route
4. Follow Express.js patterns from existing server.ts
5. All Firestore operations go through src/infrastructure/ typed wrappers
6. Services must propagate Bayesian uncertainty (CI width) — never use point estimates
7. Brain Map™ updates: Always use Beta(α,β) posterior updates
8. Error handling: use the error-handler middleware pattern
9. Rate limiting: use role-based rate limiting from middleware
10. Follow the canonical pipeline: Observe → Model → Decide → Generate → Record → Improve

Generate COMPLETE file contents for each file.`,
      {
        files: [
          'src/api/server.ts',
          'src/api/middleware/auth.ts',
          'src/api/middleware/validation.ts',
          'src/api/middleware/rate-limit.ts',
          'src/api/middleware/error-handler.ts',
          'src/infrastructure/firebase.ts',
          'src/lib/pipeline.ts',
        ],
        wikiPages: [
          'api-infrastructure',
          'api-infrastructure-api',
          'api-infrastructure-security',
          'api-infrastructure-infrastructure',
          'core-intelligence-engine',
        ],
      }
    );

    if (skillsLoaded.length > 0) {
      logger.info(`⚙️ Skills loaded: ${skillsLoaded.join(', ')}`, this.role);
    }

    try {
      const response = await this.callLLM(userPrompt, systemPrompt, {
        maxOutputTokens: 65536,
        temperature: 0.2,
      });
      totalTokens += response.tokensUsed.total;

      const files = this.parseAndApplyFiles(response, task.id);

      if (files.length === 0) {
        return this.result(false, [], 'No files generated by backend agent', totalTokens, 1, skillsLoaded);
      }

      logger.info(`⚙️ Generated ${files.length} backend files`, this.role);
      return this.result(true, files, `Generated ${files.length} backend files`, totalTokens, 1, skillsLoaded);
    } catch (error) {
      const msg = (error as Error).message;
      logger.error(`⚙️ Failed: ${msg}`, this.role);
      return this.result(false, [], msg, totalTokens, 1, skillsLoaded);
    }
  }
}
