/**
 * SANKALP-AEI Agent System — Frontend Agent
 * Specializes in Next.js pages, React components, CSS, and UX.
 * Enhanced with:
 *   - Dynamic skill injection (React, Three.js, Tailwind, etc.)
 *   - Design reference injection from agents/design/ via DesignLoader
 *     → Automatically detects which screen(s) the task targets and injects
 *       the DESIGN.md spec + reference code.html into the LLM context window.
 */

import { BaseAgent, type AgentExecutionResult } from './base-agent.js';
import { AgentRole, type TaskNode } from '../llm/models.js';
import { DesignLoader } from '../design/design-loader.js';
import { logger } from '../utils/logger.js';

export class FrontendAgent extends BaseAgent {
  private designLoader: DesignLoader;

  constructor(...args: ConstructorParameters<typeof BaseAgent>) {
    super(...args);
    this.designLoader = new DesignLoader(this.projectRoot);
  }

  async execute(task: TaskNode): Promise<AgentExecutionResult> {
    logger.info(`🎨 Starting: ${task.name}`, this.role);
    let totalTokens = 0;

    // ── Detect relevant design reference(s) for this task ──────────────────
    const designAssets = this.designLoader.loadDesignForTask(task.description + ' ' + task.name);
    const designContext = designAssets.length > 0
      ? this.designLoader.formatAsContext(designAssets)
      : '';

    if (designAssets.length > 0) {
      logger.info(
        `🎨 Design refs loaded: ${designAssets.map(a => a.screenName).join(', ')}`,
        this.role,
      );
    }

    // ── Build prompt with skills + design context ───────────────────────────
    const { systemPrompt, userPrompt, skillsLoaded } = this.buildPrompt(
      `You are building the frontend for SANKALP-AEI, an adaptive educational intelligence system.

## Task
${task.description}

## Requirements
1. Use Next.js App Router with TypeScript (strict, no \`any\`)
2. **Design System — "The Cognitive Architect" (MANDATORY)**:
   - Color palette: primary (#702ae1), primary-container (#b28cff), surface (#EBEDF0), etc. — see design spec below
   - Fonts: Manrope (headlines/display) + Inter (body/labels) — both MUST be imported
   - Neumorphic shadows: use \`neumorphic-flat\` / \`neumorphic-inset\` / \`neumorphic-pressed\` CSS classes
   - **Strict No-Line Rule**: NO 1px solid borders for containment — use background shifts or ghost borders (outline-variant/15% only)
   - All cards must use \`rounded-2xl\` or \`rounded-3xl\` minimum (no sharp corners)
   - Primary CTA buttons: gradient from #702ae1 to #b28cff, pill-shaped
   - Icon circles: icons inside \`w-10 h-10 rounded-full neumorphic-inset flex items-center justify-center\`
   - Metadata labels: all-caps, tracking-widest, Inter, 10px weight-900
3. Use functional components only with TypeScript
4. Import types from '@/types' or '../../types'
5. Every component needs responsive layout (12-col grid)
6. CSS: Tailwind classes (PostCSS + Tailwind) with design system tokens
7. Brain Map™ visualizations: Beta(α,β) distributions — never point estimates
8. Student portals: prioritize micro-interactions (\`hover:scale-[1.02]\`, transitions)
9. Teacher/parent portals: prioritize data clarity, confidence interval bands
10. Material Symbols Outlined for icons (filled: \`font-variation-settings: 'FILL' 1\`)

${designAssets.length > 0 ? `## ⚠️ CRITICAL: Reference Design Assets
The following are EXACT designs from the design team. Your React/Next.js implementation
MUST faithfully replicate their visual language — colors, layout, shadows, typography.
Do NOT invent a different visual style. Treat the reference HTML as your implementation guide.

${designContext}` : ''}

Generate COMPLETE file contents for each file that needs to be created or modified.`,
      {
        files: [
          'frontend/src/app/layout.tsx',
          'frontend/src/app/page.tsx',
          'frontend/src/app/globals.css',
          'frontend/next.config.ts',
          'frontend/package.json',
        ],
        wikiPages: [
          'frontend-application',
          'frontend-application-src',
          'frontend-application-ux',
          'frontend-application-design-prompts',
        ],
        additionalText: designContext, // also pass through the helper method
      }
    );

    if (skillsLoaded.length > 0) {
      logger.info(`🎨 Skills loaded: ${skillsLoaded.join(', ')}`, this.role);
    }

    try {
      const response = await this.callLLM(userPrompt, systemPrompt, {
        maxOutputTokens: 65536,
        temperature: 0.3,
      });
      totalTokens += response.tokensUsed.total;

      const files = this.parseAndApplyFiles(response, task.id);

      if (files.length === 0) {
        return this.result(false, [], 'No files generated by frontend agent', totalTokens, 1, skillsLoaded);
      }

      logger.info(`🎨 Generated ${files.length} frontend files`, this.role);
      return this.result(true, files, `Generated ${files.length} frontend files`, totalTokens, 1, skillsLoaded);
    } catch (error) {
      const msg = (error as Error).message;
      logger.error(`🎨 Failed: ${msg}`, this.role);
      return this.result(false, [], msg, totalTokens, 1, skillsLoaded);
    }
  }
}
