
import fs from 'fs';
import path from 'path';

// --- Configuration ---
const INTELLIGENCE_TYPES_PATH = 'src/types/intelligence.ts';
const ML_DATA_PATH = 'src/ml/training/training_data.csv';

// --- Logic ---

function parseCSVHeaders(filePath: string): string[] {
  if (!fs.existsSync(filePath)) {
    console.error(`Error: CSV file not found at ${filePath}`);
    return [];
  }
  const content = fs.readFileSync(filePath, 'utf-8');
  const firstLine = content.split('\n')[0];
  return firstLine.split(',').map(h => h.trim());
}

function parseInterfaceFields(filePath: string, interfaceName: string): string[] {
  if (!fs.existsSync(filePath)) {
    console.error(`Error: Types file not found at ${filePath}`);
    return [];
  }
  const content = fs.readFileSync(filePath, 'utf-8');
  // Simple regex to find interface block
  const regex = new RegExp(`export interface ${interfaceName} {([\\s\\S]*?)}`, 'm');
  const match = content.match(regex);

  if (!match) {
    console.error(`Error: Interface ${interfaceName} not found in ${filePath}`);
    return [];
  }

  const block = match[1];
  const fields: string[] = [];

  // Parse lines like "  fieldName: type;"
  block.split('\n').forEach(line => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('//') || trimmed.startsWith('/*')) return;

    // Extract field name before colon or optional marker ?
    const fieldMatch = trimmed.match(/^([a-zA-Z0-9_]+)\??:/);
    if (fieldMatch) {
      fields.push(fieldMatch[1]);
    }
  });

  return fields;
}

function main() {
  console.log('# Database Schema Migration Risk Analysis\n');
  console.log('Generated by: `scripts/analyze-schema-risks.ts`\n');

  const mlFeatures = parseCSVHeaders(ML_DATA_PATH);
  const tsFields = parseInterfaceFields(INTELLIGENCE_TYPES_PATH, 'MasterySignal');

  if (mlFeatures.length === 0 || tsFields.length === 0) {
    console.log('Error: Could not parse input files. Aborting analysis.');
    return;
  }

  console.log('## ML Model Feature Requirements');
  console.log('derived from `src/ml/training/training_data.csv` headers');
  mlFeatures.forEach(f => console.log(`- ${f}`));
  console.log('');

  console.log('## Current Frontend Data Schema');
  console.log('derived from `src/types/intelligence.ts` (MasterySignal interface)');
  tsFields.forEach(f => console.log(`- ${f}`));
  console.log('');

  console.log('## Gap Analysis & Risk Assessment');

  const mapping: Record<string, string | null> = {};
  const missing: string[] = [];
  const riskMatrix: Array<{ feature: string; status: string; risk: string }> = [];

  // Hardcoded known mappings (snake_case -> camelCase)
  const knownMappings: Record<string, string> = {
    'avg_quiz_score': 'score',
    'attempts_per_topic': 'attempts',
    'days_since_last_revision': 'daysSinceRevision',
    'mastered': 'needsRevision' // Inverse logic, but related
  };

  mlFeatures.forEach(feature => {
    let match = null;

    // Check exact match
    if (tsFields.includes(feature)) {
      match = feature;
    }
    // Check known mapping
    else if (knownMappings[feature] && tsFields.includes(knownMappings[feature])) {
      match = knownMappings[feature];
    }

    if (match) {
      mapping[feature] = match;
      riskMatrix.push({ feature, status: `Mapped to \`${match}\``, risk: 'LOW' });
    } else {
      missing.push(feature);
      riskMatrix.push({ feature, status: 'MISSING', risk: 'HIGH' });
    }
  });

  // Output Matrix
  console.log('| ML Feature | Schema Field | Risk Level | Mitigation |');
  console.log('|---|---|---|---|');
  riskMatrix.forEach(item => {
    let mitigation = '';
    if (item.risk === 'HIGH') {
      mitigation = 'Must include this column in new DB schema and ensure data collection pipeline populates it.';
    } else {
        mitigation = 'Ensure name transformation logic (snake_case to camelCase) is implemented correctly.';
    }
    console.log(`| \`${item.feature}\` | ${item.status} | **${item.risk}** | ${mitigation} |`);
  });

  console.log('\n## Critical Findings');
  if (missing.length > 0) {
    console.log(`\n**CRITICAL RISK**: The following ML features are MISSING from the current frontend/type schema:`);
    missing.forEach(m => console.log(`- \`${m}\``));
    console.log('\nThese fields must be persisted in the database schema (e.g., in a `TopicAttempt` or `StudentMastery` table) to support future model retraining. If they are not stored, the ML model cannot be retrained effectively.');
  } else {
    console.log('\nAll ML features appear to be covered by the current schema.');
  }

  // Backward Compatibility Check
  console.log('\n## Backward Compatibility Check');
  console.log('- **Synthetic Data**: The pending DB migration must ensure that `training_data.csv` can be loaded or replicated.');
  console.log('- **Rollback Safety**: If migration fails, ensure the app can fallback to `mock-db.ts` which uses `src/types/intelligence.ts`. The missing fields suggest `mock-db.ts` might be insufficient for *training* but fine for *inference* if the model handles missing features (imputation) or if the model is only used for prediction on features available at runtime.');

  // Note: train_mastery_model.py uses these for training. Inference (prediction) happens in... well, we haven't seen inference code yet, maybe it's in `src/ml/inference`?
  // If inference also needs these features, and they are missing from `StudentIntelligence`, then the app might be broken or using defaults.
  // Actually, `StudentIntelligence` is the *output* of the backend to the frontend.
  // The backend (ML bridge) likely has access to the raw data (or should).
  // But if `src/types` defines the contract, and the frontend sends data back? No, usually frontend sends events.
  // The risk is: "When implemented, migrations must not break existing synthetic data or ML feature extraction."

}

main();
