
import fs from 'fs';
import path from 'path';

const TARGET_DIRS = ['src/app', 'src/components'];
// Removed 'g' flag to avoid statefulness issues with .test() inside loops
const ZOD_PATTERNS = [
  { name: 'min', regex: /\.min\(\s*\d+\s*\)/, advice: 'Add a custom error message to .min()' },
  { name: 'max', regex: /\.max\(\s*\d+\s*\)/, advice: 'Add a custom error message to .max()' },
  { name: 'length', regex: /\.length\(\s*\d+\s*\)/, advice: 'Add a custom error message to .length()' },
  { name: 'email', regex: /\.email\(\s*\)/, advice: 'Add a custom error message to .email()' },
  { name: 'url', regex: /\.url\(\s*\)/, advice: 'Add a custom error message to .url()' },
  { name: 'uuid', regex: /\.uuid\(\s*\)/, advice: 'Add a custom error message to .uuid()' },
  { name: 'cuid', regex: /\.cuid\(\s*\)/, advice: 'Add a custom error message to .cuid()' },
  // regex is tricky without g if we want to match strictly, but for audit it's okay.
  // We look for .regex(/.../) with no second arg.
  // A simple heuristic: .regex( followed by / and ending with ) without a comma string
  { name: 'regex', regex: /\.regex\(\s*\/[^/]+\/[a-z]*\s*\)/, advice: 'Add a custom error message to .regex()' },
];

function scanFile(filePath: string) {
  const content = fs.readFileSync(filePath, 'utf-8');
  const issues: string[] = [];

  const lines = content.split('\n');
  lines.forEach((line, index) => {
    const trimmed = line.trim();
    if (trimmed.startsWith('//') || trimmed.startsWith('/*') || trimmed.startsWith('*')) return;

    ZOD_PATTERNS.forEach(pattern => {
      if (pattern.regex.test(line)) {
        issues.push(`Line ${index + 1}: Found ${pattern.name} validation without custom message.`);
      }
    });
  });

  return issues;
}

function walkDir(dir: string, fileList: string[] = []) {
  if (!fs.existsSync(dir)) return fileList;
  const files = fs.readdirSync(dir);
  files.forEach(file => {
    const filePath = path.join(dir, file);
    const stat = fs.statSync(filePath);
    if (stat.isDirectory()) {
      walkDir(filePath, fileList);
    } else {
      if (file.endsWith('.ts') || file.endsWith('.tsx')) {
        fileList.push(filePath);
      }
    }
  });
  return fileList;
}

function main() {
  console.log('# Form Validation Audit Report\n');
  console.log('Generated by: `scripts/audit-form-validation.ts`\n');

  let totalIssues = 0;
  let filesWithIssues = 0;

  // We need to flatten the list of files from all target dirs
  let allFiles: string[] = [];
  TARGET_DIRS.forEach(dir => {
    allFiles = allFiles.concat(walkDir(dir));
  });

  allFiles.forEach(file => {
    const issues = scanFile(file);
    if (issues.length > 0) {
      console.log(`## ${file}`);
      issues.forEach(issue => console.log(`- ${issue}`));
      console.log('');
      totalIssues += issues.length;
      filesWithIssues++;
    }
  });

  console.log('## Summary');
  console.log(`- Total Files with Issues: ${filesWithIssues}`);
  console.log(`- Total Issues Found: ${totalIssues}`);

  if (totalIssues === 0) {
    console.log('\nNo issues found! All validations appear to have custom messages (or were not detected by this simple audit).');
  } else {
      console.log('\n## Recommendations');
      console.log('1. Review each file listed above.');
      console.log('2. Add a second argument to Zod validators string, e.g., `.min(8, "Password must be at least 8 characters")`.');
      console.log('3. Ensure error messages are plain language and actionable.');
  }
}

main();
