
import { generateQuiz } from '../src/ai/flows/adaptive-quiz-engine';
import fs from 'fs';
import path from 'path';

async function auditQuizDifficulty() {
  console.log('Starting Quiz Difficulty Audit...');

  const reportPath = path.join(process.cwd(), 'reports', 'QUIZ_DIFFICULTY_ALIGNMENT_REPORT.md');
  const reportDir = path.dirname(reportPath);

  if (!fs.existsSync(reportDir)) {
    fs.mkdirSync(reportDir, { recursive: true });
  }

  let reportContent = `# Quiz Question Difficulty Calibration Report

## Overview
This report audits the alignment between requested quiz difficulty and the actual difficulty of questions generated by the Adaptive Quiz Engine.

## Methodology
- Attempted to generate quizzes for "Easy", "Medium", and "Hard" difficulties.
- (Intended) Use an LLM evaluator to rate the complexity of generated questions.
- Analyzed the prompt structure for difficulty control mechanisms.

## Findings

`;

  try {
    // Attempt generation
    console.log('Attempting to generate "Easy" quiz...');
    // We expect this to fail without an API key
    await generateQuiz({
      topic: 'Algebra',
      numQuestions: 1,
      educationLevel: 'High School',
      difficulty: 'Easy'
    });

    // If it succeeds (e.g. mock mode), we would analyze it here.
    reportContent += `### Runtime Analysis
Generation successful. (Further analysis would require a secondary LLM call which is also likely limited).
`;

  } catch (error: any) {
    console.log('Generation failed as expected (no API key). Proceeding with static analysis.');
    reportContent += `### Runtime Analysis
**Status**: Skipped due to missing API credentials.
**Error**: ${error.message}

### Static Analysis of Control Mechanisms
The Adaptive Quiz Engine uses a **Zero-Shot Prompting** strategy to control difficulty.

**Prompt Template**:
\`\`\`text
The quiz should be suitable for a "{{educationLevel}}" level.
The questions should have a difficulty of "{{difficulty}}".
\`\`\`

**Risk Assessment**:
- **High Risk of Drift**: Relying solely on the word "Easy" or "Hard" without examples (Few-Shot) or explicit constraints (Bloom's Taxonomy level, vocabulary size, sentence complexity) leads to subjective interpretation by the LLM.
- **Model Dependency**: Different models (e.g., Gemini 1.5 vs 2.0) will interpret "Hard" differently, causing calibration drift when models are updated.
- **No Feedback Loop**: There is no post-generation validation step to check if the generated questions actually match the target difficulty.

`;
  }

  // Recommendations
  reportContent += `## Recommendations

1.  **Implement Few-Shot Prompting**:
    - Include 3-5 examples of "Easy", "Medium", and "Hard" questions in the prompt to ground the model's understanding.

2.  **Use Objective Constraints**:
    - Define difficulty by Bloom's Taxonomy (e.g., Easy = Recall, Medium = Application, Hard = Analysis).
    - Add constraints on question length or complexity (e.g., "Easy: Single-step problems", "Hard: Multi-step word problems").

3.  **Post-Generation Calibration**:
    - Implement a "Critic" flow where a second LLM (or a smaller, cheaper one) rates the difficulty of the generated questions. If the rating mismatches, regenerate or discard.

4.  **User Feedback Loop**:
    - Collect student performance data (pass rates per question) to empirically measure difficulty and adjust the "difficulty label" in the database over time.
`;

  fs.writeFileSync(reportPath, reportContent);
  console.log(`Report generated at ${reportPath}`);
}

auditQuizDifficulty().catch(console.error);
