
import * as fs from 'fs';
import * as path from 'path';
import { extractMasteryFeatures, StudentHistory, RawQuizResult } from '../src/ml/features/student_features';

const TRAINING_DATA_PATH = path.join(process.cwd(), 'src/ml/training/training_data.csv');
const REPORT_PATH = path.join(process.cwd(), 'FEATURE_DRIFT_REPORT.md');

interface FeatureStats {
    min: number;
    max: number;
    mean: number;
    count: number;
    nullCount: number;
}

type TrainingSchema = Record<string, FeatureStats>;

function parseCSV(content: string): Record<string, number[]> {
    const lines = content.trim().split('\n');
    const headers = lines[0].split(',').map(h => h.trim());
    const data: Record<string, number[]> = {};

    headers.forEach(h => data[h] = []);

    for (let i = 1; i < lines.length; i++) {
        const line = lines[i].trim();
        if (!line) continue;
        const values = line.split(',');
        headers.forEach((h, idx) => {
            const val = parseFloat(values[idx]);
            if (!isNaN(val)) {
                data[h].push(val);
            }
        });
    }
    return data;
}

function calculateStats(data: Record<string, number[]>): TrainingSchema {
    const schema: TrainingSchema = {};

    for (const [feature, values] of Object.entries(data)) {
        if (values.length === 0) continue;

        const sorted = [...values].sort((a, b) => a - b);
        const sum = values.reduce((a, b) => a + b, 0);

        schema[feature] = {
            min: sorted[0],
            max: sorted[sorted.length - 1],
            mean: sum / values.length,
            count: values.length,
            nullCount: 0 // CSV parser skipped NaNs, but effectively we assume training data is clean
        };
    }
    return schema;
}

function checkDrift(featureName: string, value: number, stats: FeatureStats): string[] {
    const issues: string[] = [];

    // Check range with some tolerance (e.g. 5%) or strict?
    // Using strict for now as these are synthetic constraints.

    if (value < stats.min) {
        // Special case: 0 is often a default value. If min > 0, then 0 is a drift.
        issues.push(`Value ${value} is below training min ${stats.min}`);
    }
    if (value > stats.max) {
        issues.push(`Value ${value} is above training max ${stats.max}`);
    }

    return issues;
}

async function main() {
    console.log('🔍 Starting Feature Drift Detection...');

    // 1. Load Training Data Schema
    if (!fs.existsSync(TRAINING_DATA_PATH)) {
        console.error(`❌ Training data not found at ${TRAINING_DATA_PATH}`);
        process.exit(1);
    }

    const csvContent = fs.readFileSync(TRAINING_DATA_PATH, 'utf-8');
    const columns = parseCSV(csvContent);
    const schema = calculateStats(columns);

    console.log('✅ Training Schema Inferred.');

    // 2. Define Scenarios
    const now = new Date();
    const dayMs = 24 * 60 * 60 * 1000;

    const scenarios: Array<{name: string, history: StudentHistory}> = [
        {
            name: "New Student (No History)",
            history: {
                quizResults: [],
                lastLoginDate: now,
                registrationDate: now
            }
        },
        {
            name: "Returning Student (Inactive 100 days)",
            history: {
                quizResults: [{
                    topic: 'math',
                    score: 0.8,
                    timestamp: new Date(now.getTime() - 100 * dayMs),
                    timeSpent: 60,
                    questionsAttempted: 10
                }],
                lastLoginDate: now,
                registrationDate: new Date(now.getTime() - 200 * dayMs)
            }
        },
        {
            name: "Speedy Guesser (Fast times)",
            history: {
                quizResults: [{
                    topic: 'math',
                    score: 0.3,
                    timestamp: now,
                    timeSpent: 5, // 5 seconds total for 10 questions? = 0.5s per question
                    questionsAttempted: 10
                }],
                lastLoginDate: now,
                registrationDate: now
            }
        },
         {
            name: "Minimal Attempt (1 question)",
            history: {
                quizResults: [{
                    topic: 'math',
                    score: 0.5,
                    timestamp: now,
                    timeSpent: 10,
                    questionsAttempted: 1
                }],
                lastLoginDate: now,
                registrationDate: now
            }
        }
    ];

    // 3. Analyze
    let reportContent = `# Feature Drift Report\n\nGenerated by \`scripts/detect-feature-drift.ts\`\n\n`;
    reportContent += `| Feature | Scenario | Value | Training Range | Drift Severity | Issue |\n`;
    reportContent += `|---|---|---|---|---|---|\n`;

    let hasDrift = false;

    for (const scenario of scenarios) {
        const features = extractMasteryFeatures('math', scenario.history, now);

        for (const [key, val] of Object.entries(features)) {
            if (!schema[key]) continue; // Ignore features not in training data (target 'mastered' is in schema but not features)

            const stats = schema[key];
            const issues = checkDrift(key, val as number, stats);

            if (issues.length > 0) {
                hasDrift = true;
                for (const issue of issues) {
                    let severity = "LOW";
                    const numVal = val as number;

                    // Severity Heuristics
                    if (key === 'days_since_last_revision' && numVal > 30) severity = "CRITICAL"; // Huge outlier
                    if (key === 'avg_quiz_score' && (numVal < 0 || numVal > 1)) severity = "CRITICAL";
                    if (key === 'attempts_per_topic' && numVal === 0) severity = "HIGH"; // Missing data handling
                    if (key === 'time_spent_per_question' && numVal < 1) severity = "HIGH"; // Physically impossible/implausible

                    reportContent += `| \`${key}\` | ${scenario.name} | ${numVal.toFixed(2)} | [${stats.min.toFixed(2)}, ${stats.max.toFixed(2)}] | **${severity}** | ${issue} |\n`;
                }
            }
        }
    }

    if (!hasDrift) {
        reportContent += `\nNo drift detected across ${scenarios.length} scenarios.\n`;
    }

    // 4. Save Report
    fs.writeFileSync(REPORT_PATH, reportContent);
    console.log(`📄 Report generated at ${REPORT_PATH}`);
}

main().catch(err => {
    console.error(err);
    process.exit(1);
});
