
import fs from 'fs';
import path from 'path';

// --- Configuration & Pricing Models ---

// Pricing based on Gemini 1.5 Flash (Proxy for 2.0/2.5 Flash)
// Rates per 1 Million Tokens
const PRICING = {
  // Text / Multimodal Input
  INPUT_TOKEN_COST: 0.075, // $0.075 per 1M input tokens
  // Text Output
  OUTPUT_TOKEN_COST: 0.30, // $0.30 per 1M output tokens

  // Audio Input (Multimodal)
  // Assumption: 1 second audio ≈ 25 tokens.
  // 1 minute = 1500 tokens.
  // Cost per minute = (1500 / 1,000,000) * $0.075 = $0.0001125 (Very cheap!)
  // However, dedicated STT is ~$0.006/min. We'll use a conservative blended rate.
  AUDIO_INPUT_COST_PER_MIN: 0.006,

  // Audio Output (TTS)
  // Standard Google Cloud TTS: ~$16.00 per 1M characters.
  // We'll use character-based pricing for TTS estimation.
  TTS_COST_PER_1M_CHARS: 16.00,
};

// Feature Usage Profiles
const FEATURES = [
  {
    name: 'Adaptive Quiz Engine',
    file: 'src/ai/flows/adaptive-quiz-engine.ts',
    inputTokens: 500, // System prompt + JSON schema + user request
    outputTokens: 550, // 10 questions * ~50 tokens + JSON overhead
    dailyFrequency: 2, // Quizzes per user per day
    audioInputMin: 0,
    audioOutputChars: 0,
    description: 'Generates 10-question quizzes based on topic.',
  },
  {
    name: 'Syllabus Generator',
    file: 'src/ai/flows/syllabus-generator.ts',
    inputTokens: 300, // Prompt + query
    outputTokens: 1200, // Structured syllabus + 5 references + strategy
    dailyFrequency: 0.1, // Infrequent (once every 10 days)
    audioInputMin: 0,
    audioOutputChars: 0,
    description: 'Creates detailed study syllabus and strategy.',
  },
  {
    name: 'Cognitive Chatbot',
    file: 'src/ai/flows/custom-cognitive-chatbot.ts',
    inputTokens: 400, // Personality + Context + History + Query
    outputTokens: 250, // Explanation
    dailyFrequency: 10, // Interactions per day
    audioInputMin: 0,
    audioOutputChars: 0,
    description: 'Explains concepts with customized persona.',
  },
  {
    name: 'Mindful Mentor',
    file: 'src/ai/flows/mindful-mentor.ts',
    inputTokens: 600, // System prompt + Student History + Concern
    outputTokens: 300, // Empathetic advice
    dailyFrequency: 1, // Once per day
    audioInputMin: 0,
    audioOutputChars: 0,
    description: 'Provides emotional support and motivation.',
  },
  {
    name: 'Smart Revision Planner',
    file: 'src/ai/flows/smart-revision-planner.ts',
    inputTokens: 300, // List of topics + metadata
    outputTokens: 200, // Explanations for top 5 topics
    dailyFrequency: 1, // Daily planning
    audioInputMin: 0,
    audioOutputChars: 0,
    description: 'Explains why specific topics need revision.',
  },
  {
    name: 'Speech-to-Speech',
    file: 'src/ai/flows/speech-to-speech.ts',
    // Flow: Audio -> STT (Gemini) -> Text -> LLM (Gemini) -> Text -> TTS (Gemini)
    // 1. Audio Input (STT)
    audioInputMin: 0.25, // 15 seconds average query
    // 2. LLM Processing
    inputTokens: 200, // Transcribed text + system prompt
    outputTokens: 150, // Concise response
    // 3. Audio Output (TTS)
    audioOutputChars: 600, // ~150 words * 4 chars/word
    dailyFrequency: 5, // Voice interactions per day
    description: 'Real-time voice conversation.',
  },
  {
    name: 'Text-to-Speech',
    file: 'src/ai/flows/text-to-speech.ts',
    inputTokens: 0,
    outputTokens: 0,
    audioInputMin: 0,
    audioOutputChars: 500, // Reading a short paragraph
    dailyFrequency: 2, // Listen to summary/explanation
    description: 'Converts text explanations to audio.',
  },
];

// --- Calculation Logic ---

function calculateFeatureCost(feature: typeof FEATURES[0]) {
  // Text Costs
  const inputCost = (feature.inputTokens / 1_000_000) * PRICING.INPUT_TOKEN_COST;
  const outputCost = (feature.outputTokens / 1_000_000) * PRICING.OUTPUT_TOKEN_COST;

  // Audio Costs
  const audioInputCost = feature.audioInputMin * PRICING.AUDIO_INPUT_COST_PER_MIN;
  const audioOutputCost = (feature.audioOutputChars / 1_000_000) * PRICING.TTS_COST_PER_1M_CHARS;

  const totalUnitCost = inputCost + outputCost + audioInputCost + audioOutputCost;
  const dailyCostPerUser = totalUnitCost * feature.dailyFrequency;

  return {
    unit: totalUnitCost,
    daily: dailyCostPerUser,
    breakdown: {
      input: inputCost,
      output: outputCost,
      audioInput: audioInputCost,
      audioOutput: audioOutputCost,
    },
  };
}

function generateReport() {
  let report = `# LLM Token Usage Cost Projection

**Domain**: Performance & Cost
**Scope**: \`src/ai/flows/\` (Genkit LLM Calls)
**Date**: ${new Date().toLocaleDateString()}
**Generated By**: \`scripts/estimate-token-usage.ts\`

---

## 1. Executive Summary

This report projects the monthly costs for LLM and Audio features based on estimated usage patterns.

**Key Findings**:
*   **Text-based flows** are highly cost-effective (avg < $0.0005 per call).
*   **Audio features (Speech-to-Speech)** are the primary cost driver, costing **~20-50x more** than text interactions.
*   **Scaling Risk**: At 10,000 users, monthly costs could exceed **$3,000** if speech features are uncapped.

---

## 2. Pricing Assumptions (Gemini Flash Tier)

| Metric | Rate | Unit |
| :--- | :--- | :--- |
| **Input (Text)** | $${PRICING.INPUT_TOKEN_COST.toFixed(3)} | Per 1M Tokens |
| **Output (Text)** | $${PRICING.OUTPUT_TOKEN_COST.toFixed(2)} | Per 1M Tokens |
| **Audio Input** | $${PRICING.AUDIO_INPUT_COST_PER_MIN.toFixed(3)} | Per Minute |
| **Audio Output (TTS)**| $${PRICING.TTS_COST_PER_1M_CHARS.toFixed(2)} | Per 1M Characters |

---

## 3. Per-Feature Cost Analysis

`;

  let totalDailyCostPerUser = 0;

  report += `| Feature | Input Tokens | Output Tokens | Audio In (min) | Audio Out (chars) | Unit Cost ($) | Daily Freq | Daily Cost ($) |
| :--- | :---: | :---: | :---: | :---: | :---: | :---: | :---: |
`;

  FEATURES.forEach(feature => {
    const costs = calculateFeatureCost(feature);
    totalDailyCostPerUser += costs.daily;

    report += `| **${feature.name}** | ${feature.inputTokens} | ${feature.outputTokens} | ${feature.audioInputMin > 0 ? feature.audioInputMin.toFixed(2) : '-'} | ${feature.audioOutputChars > 0 ? feature.audioOutputChars : '-'} | **$${costs.unit.toFixed(5)}** | ${feature.dailyFrequency} | $${costs.daily.toFixed(4)} |\n`;
  });

  report += `
---

## 4. Scaled Cost Projections (Monthly)

| User Base | Daily Cost | Monthly Cost (30 days) | Annual Cost |
| :--- | :---: | :---: | :---: |
| **1 User** | $${totalDailyCostPerUser.toFixed(4)} | **$${(totalDailyCostPerUser * 30).toFixed(2)}** | $${(totalDailyCostPerUser * 365).toFixed(2)} |
| **100 Users** | $${(totalDailyCostPerUser * 100).toFixed(2)} | **$${(totalDailyCostPerUser * 100 * 30).toFixed(2)}** | $${(totalDailyCostPerUser * 100 * 365).toFixed(2)} |
| **1,000 Users** | $${(totalDailyCostPerUser * 1000).toFixed(2)} | **$${(totalDailyCostPerUser * 1000 * 30).toFixed(2)}** | $${(totalDailyCostPerUser * 1000 * 365).toFixed(2)} |
| **10,000 Users** | $${(totalDailyCostPerUser * 10000).toFixed(2)} | **$${(totalDailyCostPerUser * 10000 * 30).toFixed(2)}** | $${(totalDailyCostPerUser * 10000 * 365).toFixed(2)} |

---

## 5. Detailed Breakdown & Recommendations

### High-Cost Drivers
1.  **Speech-to-Speech**: Accounts for a significant portion of the budget due to TTS costs.
    *   *Recommendation*: Implement caching for common responses. Use standard voices where possible. Limit free tier usage.
2.  **Syllabus Generator**: High output token count (1000+).
    *   *Recommendation*: Cache generated syllabi for popular subjects (e.g., "Algebra I", "AP Biology").

### Optimization Strategies
1.  **Caching**: Implement Redis/Firestore caching for \`Syllabus Generator\` and \`Text-to-Speech\` (hash of text input).
2.  **Rate Limiting**: Enforce stricter rate limits on Audio endpoints.
3.  **Model Selection**: Ensure \`gemini-1.5-flash\` or \`gemini-2.0-flash\` is explicitly used over Pro versions for high-volume flows.

---
*Report automatically generated by \`scripts/estimate-token-usage.ts\`*
`;

  const outputPath = path.join(process.cwd(), 'LLM_TOKEN_USAGE_COST_PROJECTION.md');
  fs.writeFileSync(outputPath, report);
  console.log(`Report generated at: ${outputPath}`);
}

generateReport();
