import fs from 'fs';
import path from 'path';

const RULES_PATH = 'firestore.rules';
const REPORT_PATH = 'FIRESTORE_SECURITY_REPORT.md';

interface TestContext {
  auth?: { uid: string; token?: any };
  resource?: { data: any };
  request?: { resource?: { data: any } };
  path: string;
  method: 'read' | 'create' | 'update' | 'delete';
}

interface TestCase {
  name: string;
  context: TestContext;
  expected: 'allow' | 'deny';
}

function simulateSecurityRules() {
  console.log('🛡️ Starting Firestore Security Rules Simulation...');

  if (!fs.existsSync(RULES_PATH)) {
    console.error(`❌ Rules file not found: ${RULES_PATH}`);
    process.exit(1);
  }

  const rulesContent = fs.readFileSync(RULES_PATH, 'utf-8');

  // Extract collections and their rules (naive parsing)
  const collectionRules: Record<string, string> = {};
  const matches = rulesContent.matchAll(/match\s+\/([a-zA-Z0-9_{}]+)\/\{[a-zA-Z0-9]+\}\s*\{([^}]+)\}/g);

  for (const match of matches) {
    collectionRules[match[1]] = match[2];
  }

  console.log(`   Found rules for collections: ${Object.keys(collectionRules).join(', ')}`);

  const testCases: TestCase[] = [
    {
      name: "Anonymous user reads user profile",
      context: { path: '/users/user123', method: 'read' },
      expected: 'deny'
    },
    {
      name: "User reads own profile",
      context: { path: '/users/user123', method: 'read', auth: { uid: 'user123' } },
      expected: 'allow'
    },
    {
      name: "User reads other's profile",
      context: { path: '/users/otherUser', method: 'read', auth: { uid: 'user123' } },
      expected: 'deny'
    },
    {
      name: "Student reads own quiz results",
      context: {
        path: '/quizResults/res1',
        method: 'read',
        auth: { uid: 'student1' },
        resource: { data: { studentId: 'student1' } }
      },
      expected: 'allow'
    },
    {
      name: "Student reads other's quiz results",
      context: {
        path: '/quizResults/res2',
        method: 'read',
        auth: { uid: 'student1' },
        resource: { data: { studentId: 'student2' } }
      },
      expected: 'deny'
    },
    {
      name: "Teacher reads student quiz results",
      context: {
        path: '/quizResults/res1',
        method: 'read',
        auth: { uid: 'teacher1' },
        resource: { data: { studentId: 'student1', teacherId: 'teacher1' } }
      },
      expected: 'allow'
    }
  ];

  let reportContent = `# Firestore Security Rules Simulation Report\n\n**Date:** ${new Date().toISOString()}\n\n## Simulation Results\n\n| Scenario | Path | Method | Expected | Actual | Status |\n|---|---|---|---|---|---|\n`;

  let passed = 0;

  for (const test of testCases) {
    const collection = test.context.path.split('/')[1];
    const ruleBlock = collectionRules[collection];

    let actual: 'allow' | 'deny' = 'deny';

    if (ruleBlock) {
      // Simulate evaluation
      actual = evaluate(ruleBlock, test.context, rulesContent);
    } else {
        // Default deny if no match found
        actual = 'deny';
    }

    const status = actual === test.expected ? '✅ Pass' : '❌ Fail';
    if (status === '✅ Pass') passed++;

    reportContent += `| ${test.name} | \`${test.context.path}\` | ${test.context.method.toUpperCase()} | ${test.expected.toUpperCase()} | ${actual.toUpperCase()} | ${status} |\n`;
  }

  reportContent += `\n## Summary\n- **Total Scenarios:** ${testCases.length}\n- **Passed:** ${passed}\n- **Failed:** ${testCases.length - passed}\n\n## Coverage Analysis\nThis report is generated by a static simulation script that approximates Firestore rule logic. It verifies that critical access control patterns (Ownership, Authentication) are structurally present.\n`;

  fs.writeFileSync(REPORT_PATH, reportContent);
  console.log(`✅ Report generated: ${REPORT_PATH}`);
}

function evaluate(ruleBlock: string, context: TestContext, fullRules: string): 'allow' | 'deny' {
  // Naive evaluator: Checks if the condition string effectively equates to true given the context
  // This is NOT a real CEL parser, but a heuristic checker for common patterns.

  const methodRegex = new RegExp(`allow\\s+([^:]*${context.method}[^:]*):\\s+if\\s+([^;]+);`, 'g');
  const match = methodRegex.exec(ruleBlock);

  if (!match) return 'deny'; // No allow rule for this method

  let condition = match[2].trim();

  // Replace helpers with rough logic
  // "isOwner(userId)" -> matches path param if it exists in args

  const userIdFromPath = context.path.split('/').pop();

  if (condition.includes('isOwner(')) {
     // Extract arg name
     const argMatch = condition.match(/isOwner\(([^)]+)\)/);
     if (argMatch) {
         const arg = argMatch[1];
         // If arg matches the path param variable name (e.g. userId), we compare auth.uid to path param
         // For simulation, we assume if the test context auth.uid matches the last segment of path, it's owner
         if (context.auth && context.auth.uid === userIdFromPath) {
             condition = condition.replace(/isOwner\([^)]+\)/g, 'true');
         } else {
             condition = condition.replace(/isOwner\([^)]+\)/g, 'false');
         }
     }
  }

  if (condition.includes('isAuthenticated()')) {
      if (context.auth) condition = condition.replace('isAuthenticated()', 'true');
      else condition = condition.replace('isAuthenticated()', 'false');
  }

  // Normalize whitespace for easier matching
  const normalizedCondition = condition.replace(/\s+/g, ' ');

  // Handle resource.data.studentId == request.auth.uid
  if (normalizedCondition.includes('resource.data.studentId == request.auth.uid')) {
      if (context.resource && context.auth && context.resource.data.studentId === context.auth.uid) {
          condition = condition.replace(/resource\.data\.studentId\s*==\s*request\.auth\.uid/g, 'true');
      } else {
          condition = condition.replace(/resource\.data\.studentId\s*==\s*request\.auth\.uid/g, 'false');
      }
  }

  // Handle teacher checks (mocking logic)
  if (normalizedCondition.includes('resource.data.teacherId == request.auth.uid')) {
       if (context.resource && context.auth && context.resource.data.teacherId === context.auth.uid) {
          condition = condition.replace(/resource\.data\.teacherId\s*==\s*request\.auth\.uid/g, 'true');
      } else {
          condition = condition.replace(/resource\.data\.teacherId\s*==\s*request\.auth\.uid/g, 'false');
      }
  }


  // Simplify boolean logic by using eval() on the sanitized string
  try {
      // Remove whitespace/newlines for cleaner string
      const evalable = condition
        .replace(/\s+/g, ' ')
        // Remove any remaining unreplaced function calls/properties with false (conservative)
        .replace(/[a-zA-Z0-9_]+\([^)]*\)/g, 'false')
        .replace(/[a-zA-Z0-9_.]+/g, (match) => {
            if (match === 'true' || match === 'false') return match;
            return 'false'; // any variable/path not replaced is considered false/undefined
        });

      // Use Function constructor for safer eval
      const result = new Function(`return ${evalable}`)();
      return result ? 'allow' : 'deny';
  } catch (e) {
      // console.log(`Eval error for "${condition}": ${e}`);
      return 'deny';
  }
}


simulateSecurityRules();
