
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';

const TARGET_DIR = 'src/ai/flows';

function computeHash(content: string): string {
  return crypto.createHash('sha256').update(content).digest('hex');
}

function scanForPrompts(dir: string) {
  if (!fs.existsSync(dir)) return [];
  const files = fs.readdirSync(dir);
  const results: Array<{ file: string; promptName: string; hash: string; contentSnippet: string }> = [];

  files.forEach(file => {
    if (!file.endsWith('.ts')) return;
    const filePath = path.join(dir, file);
    const content = fs.readFileSync(filePath, 'utf-8');

    // Regex to find ai.definePrompt
    // We look for `ai.definePrompt({` and then extract `name: '...'` and `prompt: `...``
    // Since order can vary, we might need a better approach or just multiple regexes.
    // But assuming the convention:
    const regex = /ai\.definePrompt\(\s*\{([\s\S]*?)\}\);/g;

    let match;
    while ((match = regex.exec(content)) !== null) {
      const body = match[1];

      const nameMatch = body.match(/name:\s*['"]([^'"]+)['"]/);
      const promptMatch = body.match(/prompt:\s*`([\s\S]*?)`/);

      if (nameMatch && promptMatch) {
          const name = nameMatch[1];
          const promptContent = promptMatch[1];
          const hash = computeHash(promptContent);

          results.push({
            file: file,
            promptName: name,
            hash: hash,
            contentSnippet: promptContent.trim().substring(0, 50).replace(/\n/g, ' ') + '...'
          });
      }
    }
  });

  return results;
}

function main() {
  console.log('# LLM Prompt Template Version History\n');
  console.log('Generated by: `scripts/track-prompt-versions.ts`\n');
  console.log(`Date: ${new Date().toISOString()}\n`);

  const prompts = scanForPrompts(TARGET_DIR);

  if (prompts.length === 0) {
    console.log('No prompts found in `src/ai/flows` matching the expected pattern.');
    return;
  }

  console.log('| File | Prompt Name | Version Hash (SHA256) | Content Snippet |');
  console.log('|---|---|---|---|');

  prompts.forEach(p => {
    console.log(`| \`${p.file}\` | \`${p.promptName}\` | \`${p.hash.substring(0, 16)}\` | ${p.contentSnippet} |`);
  });

  console.log('\n## Change Log');
  console.log('To track changes, commit this file. Diffs in the "Version Hash" column indicate prompt modifications.');
}

main();
