"""
SANKALP-AEI Machine Learning Pipeline

This module exposes the core Pydantic models that define the strict data boundary
between the Node.js backend (Zod) and the Python ML ensemble (FastAPI).

Architectural Laws Enforced:
1. Bayesian Core: All mastery estimates must include Beta(α, β) parameters.
2. Uncertainty Quantification: Confidence intervals (lower, upper, width) are mandatory.
3. Strict Validation: Pydantic is used for all ingestion and egress.
"""

from typing import List, Dict, Literal
from pydantic import BaseModel, Field, model_validator

class Confidence(BaseModel):
    """
    Represents the Bayesian uncertainty of a prediction.
    Point estimates are forbidden; bounds and width must be explicitly provided.
    """
    value: float = Field(..., ge=0.0, le=1.0, description="Mean probability (α / (α + β))")
    lowerBound: float = Field(..., ge=0.0, le=1.0, description="95% Credible Interval lower bound")
    upperBound: float = Field(..., ge=0.0, le=1.0, description="95% Credible Interval upper bound")
    ciWidth: float = Field(..., ge=0.0, le=1.0, description="Width of the CI (upperBound - lowerBound)")

    @model_validator(mode='after')
    def validate_bounds(self) -> 'Confidence':
        if self.lowerBound > self.upperBound:
            raise ValueError("lowerBound cannot be greater than upperBound")
        # Ensure ciWidth is accurately calculated
        expected_width = round(self.upperBound - self.lowerBound, 4)
        actual_width = round(self.ciWidth, 4)
        if abs(expected_width - actual_width) > 0.01:
            raise ValueError(f"ciWidth ({self.ciWidth}) does not match upperBound - lowerBound ({expected_width})")
        return self

class BayesianPosterior(BaseModel):
    """
    The raw parameters of the Beta distribution generated by the ensemble meta-learner.
    """
    alpha: float = Field(..., gt=0.0, description="Success evidence parameter")
    beta: float = Field(..., gt=0.0, description="Failure evidence parameter")
    variance: float = Field(..., ge=0.0, description="Variance of the Beta distribution")

class MasteryEstimate(BaseModel):
    """
    Probabilistic estimate of a learner's mastery over a specific topic.
    """
    topicId: str = Field(..., description="Unique identifier for the knowledge graph topic")
    masteryProbability: float = Field(..., ge=0.0, le=1.0, description="Mean mastery probability")
    confidence: Confidence
    posterior: BayesianPosterior

class ForgettingEstimate(BaseModel):
    """
    Estimate of retention decay based on Ebbinghaus models and interaction history.
    """
    topicId: str
    daysUntilForget: float = Field(..., ge=0.0, description="Estimated days until mastery drops below threshold")
    retentionConfidence: Confidence
    estimatedForgetDate: str = Field(..., description="ISO-8601 timestamp")

class AttentionEstimate(BaseModel):
    """
    Risk assessment for learner disengagement or dropout.
    """
    attentionRiskClass: Literal["low", "moderate", "high", "critical"]
    dropoutProbability: float = Field(..., ge=0.0, le=1.0)
    confidence: Confidence

class PerformanceTrendEstimate(BaseModel):
    """
    Directional trend of the learner's recent performance.
    """
    direction: Literal["improving", "stable", "declining"]
    magnitude: float = Field(..., ge=0.0, le=1.0, description="Strength of the trend")

class PredictionResponse(BaseModel):
    """
    The canonical output payload from the ML pipeline, consumed by the ADK Decision Block.
    """
    learnerId: str
    generatedAt: str = Field(..., description="ISO-8601 timestamp of inference")
    masteryEstimates: List[MasteryEstimate]
    forgettingEstimates: List[ForgettingEstimate]
    attentionEstimate: AttentionEstimate
    performanceTrend: PerformanceTrendEstimate
    derivedRiskSignals: Dict[str, float] = Field(
        default_factory=dict,
        description="Additional probabilistic risk signals (e.g., 'exam_anxiety', 'concept_confusion')"
    )

class FeatureVector(BaseModel):
    """
    The 40-dimensional feature vector ingested from the Node.js FeatureEngineeringBlock.
    """
    learnerId: str
    features: List[float] = Field(..., min_length=40, max_length=40, description="Exact 40-dim feature array")
    recentInteractions: List[Dict] = Field(
        default_factory=list,
        description="Sequential interaction data for the TensorFlow LSTM/Transformer model"
    )

__all__ = [
    "Confidence",
    "BayesianPosterior",
    "MasteryEstimate",
    "ForgettingEstimate",
    "AttentionEstimate",
    "PerformanceTrendEstimate",
    "PredictionResponse",
    "FeatureVector"
]